name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run xcodebuild
      run: xcodebuild -scheme AppiumForMac -configuration Debug -derivedDataPath $GITHUB_WORKSPACE build

    - name: Upload an AppiumForMac.app
      uses: actions/upload-artifact@v2
      with:
        name: Debug_AppiumForMac
        path: ${{ github.workspace }}/appium-for-mac/appium-for-mac/Build/Products/Debug
